<a href="https://colab.research.google.com/github/wulannurafifah/Tugas-1-Scrapping-Serpapi-Text-Mining/blob/main/Data%20Uts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install google-search-results

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting google-search-results
  Downloading google_search_results-2.4.1.tar.gz (11 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from google-search-results) (2.23.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (3.0.4)
Building wheels for collected packages: google-search-results
  Building wheel for google-search-results (setup.py) ... done
  Created wheel for google-search-results: filename=google_search_results-2.4.1-py3-none-any.whl size=25789 sha256=08ddc5cd33b9e06bc48911534c0ac75dbc34f3cbcecb9b5361fc21cd81da5d6a
  Stored in directory: /root/.cache/pip/wheels/82/a3/c5/364155118f298722dff2f79ae4dd7c91e92b433ad36d6f7e0e
Successfully built google-search-results
Installing collected packages: google-search-results
Successfully installed google-search-results-2.4.1

In [2]:
from serpapi import GoogleSearch
from urllib.parse import *

In [3]:
params = {
  "engine": "google_maps",
  "q": "bakso",
  "ll": "@-7.0205424,110.401996,12.1z",
  "type": "search",
  "api_key": "f48809c40d8c47aeaf54a6e737aa67ce82d8c15af911f2e644039a0d93a2e9bd"
}

search = GoogleSearch(params)

mPosition = 0 # Angka indeks dari data
mNums = 5 # Batas jumlah data yang ditampilkan
local_results = []

while mPosition <= mNums:
  results = search.get_dict()

  for result in results["local_results"]:
    mPosition += 1
    
    if mPosition <= mNums:
      
      # Jika jumlah review kurang dari 150, maka jangan masukkan datanya
      if result["reviews"] < 150:
        mNums += 1
        continue
        
      # Append data sesuai dengan batas jumlah yang sudah ditentukan
      local_results.append({'title': result["title"],
                           'data_id': result["data_id"],
                           'reviews_total': result["reviews"]});

  if "next" in results.get("serpapi_pagination", {}):
    # Akan mengubah parameter dari 'GoogleSearch()' dengan isi parameter dari halaman selanjutnya
    search.params_dict.update(dict(parse_qsl(urlsplit(results.get("serpapi_pagination").get("next")).query)))

  else:
    break

https://serpapi.com/search

In [4]:
for lr in local_results:
  print(lr)

{'title': 'Bakso Agung Wahidin', 'data_id': '0x2e708b80bfac4137:0x23476918739afa76', 'reviews_total': 679}
{'title': 'Bakso Bang Kribo', 'data_id': '0x2e70895a61e96bdb:0x2d3adb3be8796e03', 'reviews_total': 656}
{'title': 'Bakso Kotak Suroboyo Cak Wanto', 'data_id': '0x2e708ccfd67ffc67:0xfe6e44be416fdc85', 'reviews_total': 175}
{'title': 'Bakso Bintang', 'data_id': '0x2e70894e7f3f360f:0x96b6014722fa592', 'reviews_total': 579}
{'title': 'Bakso Pak Wardi Pusat Telogorejo', 'data_id': '0x2e708ca76324ffef:0x5d40f44311d348d3', 'reviews_total': 300}

In [5]:
data = {'restaurant_name':[],
        'name':[],
        'rating':[],
        'review':[]}

for lr in local_results:
  
  params = {
    "engine": "google_maps_reviews",
    "data_id": "",
    "api_key": "f48809c40d8c47aeaf54a6e737aa67ce82d8c15af911f2e644039a0d93a2e9bd"
  }
  
  params["data_id"] = lr['data_id']

  search = GoogleSearch(params)

  mPosition = 0 # Angka indeks dari data
  mNums = 50 # Batas jumlah data yang ditampilkan

  while mPosition <= mNums:
    results = search.get_dict()

    for result in results["reviews"]:
      mPosition += 1

      if mPosition <= mNums:
        # Append data sesuai dengan batas jumlah yang sudah ditentukan
        data['restaurant_name'].append(lr['title']);
        data['name'].append(result["user"]["name"]);
        data['rating'].append(result["rating"]);
        data['review'].append(result["snippet"]);

    if "next" in results.get("serpapi_pagination", {}):
      # Akan mengubah parameter dari 'GoogleSearch()' dengan isi parameter dari halaman selanjutnya
      search.params_dict.update(dict(parse_qsl(urlsplit(results.get("serpapi_pagination").get("next")).query)))

    else:
      break
    
review_original = data['review']

https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search

In [6]:
import pandas as pd
df_original = pd.DataFrame(data)
df_original.to_csv('data_uts_textmining.csv', index=False)

In [7]:
df_original

,restaurant_name,name,rating,review
0,Bakso Agung Wahidin,Suria Nataadmadja,4.0,Quite tasty and delicious meatballs. Tasty sou...
1,Bakso Agung Wahidin,Raden Arief Nugroho,3.0,Just passed by. Can't really review. Please do...
2,Bakso Agung Wahidin,Kiera Kiera,4.0,The meatballs are great. The place is actually...
3,Bakso Agung Wahidin,Agnes Kartika,3.0,"Taste is so so, price is acceptable. Nothing s..."
4,Bakso Agung Wahidin,Victorio Sukamto,5.0,"Prime quality, clean place, good and fast serv..."
...,...,...,...,...
245,Bakso Pak Wardi Pusat Telogorejo,fransiska29,4.0,(Translated by Google) champion!! the place is...
246,Bakso Pak Wardi Pusat Telogorejo,andre santoso,4.0,(Translated by Google) One of the most famous ...
247,Bakso Pak Wardi Pusat Telogorejo,Ilham restu Kartiko,5.0,(Translated by Google) Highly recommended beca...
248,Bakso Pak Wardi Pusat Telogorejo,Hana Novita,5.0,"(Translated by Google) The taste is good, the ..."
249,Bakso Pak Wardi Pusat Telogorejo,Dee Dee,5.0,(Translated by Google) Savory & chewy beef mea...

In [8]:
review_remove_translated = []

for review in review_original:
  review_sep = review.split("(Translated by Google)")
  
  # Jika terdapat (Translated by Google)
  if review_sep[0] == "":
    review_sep = ("".join(review_sep)).split("(Original)")
    review_sep = review_sep[0]
    review = "".join(review_sep)
    
  review_remove_translated.append(review)

In [10]:
df_original

,restaurant_name,name,rating,review
0,Bakso Agung Wahidin,Suria Nataadmadja,4.0,Quite tasty and delicious meatballs. Tasty sou...
1,Bakso Agung Wahidin,Raden Arief Nugroho,3.0,Just passed by. Can't really review. Please do...
2,Bakso Agung Wahidin,Kiera Kiera,4.0,The meatballs are great. The place is actually...
3,Bakso Agung Wahidin,Agnes Kartika,3.0,"Taste is so so, price is acceptable. Nothing s..."
4,Bakso Agung Wahidin,Victorio Sukamto,5.0,"Prime quality, clean place, good and fast serv..."
...,...,...,...,...
245,Bakso Pak Wardi Pusat Telogorejo,fransiska29,4.0,(Translated by Google) champion!! the place is...
246,Bakso Pak Wardi Pusat Telogorejo,andre santoso,4.0,(Translated by Google) One of the most famous ...
247,Bakso Pak Wardi Pusat Telogorejo,Ilham restu Kartiko,5.0,(Translated by Google) Highly recommended beca...
248,Bakso Pak Wardi Pusat Telogorejo,Hana Novita,5.0,"(Translated by Google) The taste is good, the ..."
249,Bakso Pak Wardi Pusat Telogorejo,Dee Dee,5.0,(Translated by Google) Savory & chewy beef mea...